# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish

on:
  release:
    types: [published]

jobs:
  build_test_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Package AW.ClaimsExpressions
        run: dotnet pack --configuration Release /p:Version=${{ github.event.release.tag_name }}
      
      - name: Publish AW.ClaimsExpressions
        run: dotnet nuget push ./src/AW.ClaimsExpressions/bin/Release/*.nupkg --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Package AW.ClaimsExpressions.AspNetCore
        run: dotnet pack --configuration Release /p:Version=${{ github.event.release.tag_name }}

      - name: Publish AW.ClaimsExpressions.AspNetCore
        run: dotnet nuget push ./src/AW.ClaimsExpressions.AspNetCore/bin/Release/*.nupkg --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
